name: "Visual Regression"

on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - synchronize
        paths:
            - packages/core/**

permissions:
    id-token: write
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build-storybook:
        runs-on: macos-latest
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v4

            - name: Install Dependencies
              uses: ./.github/composite/install

            - name: Build Storybook
              run: pnpm build:storybook

            - name: Upload Storybook build
              uses: actions/upload-artifact@v4
              with:
                  name: storybook-static
                  path: apps/storybook/storybook-static
                  retention-days: 1
                  if-no-files-found: error

    test:
        runs-on: macos-latest
        needs: [build-storybook]
        strategy:
            fail-fast: false
            matrix:
                shard:
                    [
                        { name: firefox, project: firefox },
                        { name: safari, project: webkit },
                        { name: chrome, project: chromium },
                        { name: edge, project: chromium },
                    ]

        steps:
            - name: Git clone the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Dependencies
              uses: ./.github/composite/install

            - name: Download Storybook build
              uses: actions/download-artifact@v4
              with:
                  name: storybook-static
                  path: apps/storybook/storybook-static

            - name: Install Playwright Browsers
              run: pnpm core exec playwright install ${{ matrix.shard.project }}

            - name: Run Playwright tests
              run: pnpm core test:regressions --project="${{ matrix.shard.name }}"

            - name: Upload blob report to GitHub Actions Artifacts
              if: ${{ !cancelled() }}
              uses: actions/upload-artifact@v4
              with:
                  name: blob-report-${{ matrix.shard.name }}
                  path: packages/core/blob-report
                  retention-days: 1
